"""Control-plane views of the shared, reference-based contracts.

The authoritative definitions live in :mod:`defect_platform.contracts` so
trainer, runtime, serving, and control consumers cannot drift into separate
wire formats.  This module is a convenient control-boundary import surface.
"""

from defect_platform.contracts import (
    ArtifactRef,
    CatalogRef,
    ComponentCatalog,
    ComponentCatalogRecord,
    ComponentDefinition,
    ComponentRef,
    Error,
    ErrorOwner,
    ErrorRecord,
    ErrorRef,
    ExperimentMatrix,
    ExperimentMatrixRecord,
    ExperimentMatrixRef,
    ExperimentVariant,
    JsonPatchError,
    JsonPatchOperation,
    LifecycleState,
    OperatorProfile,
    OperatorProfileRecord,
    OperatorProfileRef,
    PatchOperation,
    Preset,
    PresetRecord,
    PresetRef,
    RecordRef,
    Reference,
    SchemaRef,
    SchemaRegistry,
    SchemaRegistryEntry,
    Status,
    StatusRecord,
    StatusRef,
    TelemetryEvent,
    TelemetryRecord,
    TelemetryRef,
    TelemetrySeverity,
    apply_json_patch,
    apply_patch,
    validate_json_patch,
    validate_patch,
)

__all__ = [
    "ArtifactRef",
    "CatalogRef",
    "ComponentCatalog",
    "ComponentCatalogRecord",
    "ComponentDefinition",
    "ComponentRef",
    "Error",
    "ErrorOwner",
    "ErrorRecord",
    "ErrorRef",
    "ExperimentMatrix",
    "ExperimentMatrixRecord",
    "ExperimentMatrixRef",
    "ExperimentVariant",
    "JsonPatchError",
    "JsonPatchOperation",
    "LifecycleState",
    "OperatorProfile",
    "OperatorProfileRecord",
    "OperatorProfileRef",
    "PatchOperation",
    "Preset",
    "PresetRecord",
    "PresetRef",
    "RecordRef",
    "Reference",
    "SchemaRef",
    "SchemaRegistry",
    "SchemaRegistryEntry",
    "Status",
    "StatusRecord",
    "StatusRef",
    "TelemetryEvent",
    "TelemetryRecord",
    "TelemetryRef",
    "TelemetrySeverity",
    "apply_json_patch",
    "apply_patch",
    "validate_json_patch",
    "validate_patch",
]
